3.0.beta3/config/routes.rb
Teste2::Application.routes.draw do |map|
  resources :tasks
  root :to => "tasks#index"

end

3.0.beta3/app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name, :description, :due_date, :finished
end

3.0.beta3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

3.0.beta3/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :js

  def index
    @task = Task.new
    respond_with(@tasks = Task.all)
  end
  
  def show
    respond_with(@task = Task.find(params[:id]))
  end
  
  def new
    respond_with(@task = Task.new)
  end
  
  def create
    @task = Task.new(params[:task])
    flash[:notice] = "Successfully created task." if @task.save
    respond_with @task
  end
  
  def edit
    respond_with(@task = Task.find(params[:id]))
  end
  
  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      flash[:notice] = "Successfully updated task."
    end
    respond_with @task 
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "Successfully destroyed task."
    respond_with @task
  end
end

3.0.beta3/app/helpers/application_helper.rb
module ApplicationHelper
end

3.0.beta3/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

3.0.beta3/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

3.0.beta3/app/helpers/tasks_helper.rb
module TasksHelper
end

3.0.beta3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" %>
    <%= javascript_include_tag "rails" %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

3.0.beta3/app/views/tasks/_form.html.erb
<%= form_for @task, :remote => true do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 3 %>
  </p>
  <p>
    <%= f.label :due_date %><br />
    <%= f.datetime_select :due_date %>
  </p>
  <p>
    <%= f.label :finished %><br />
    <%= f.check_box :finished %>
  </p>
  <p><%= f.submit %> <input type="reset" value="Reset"/></p>
<% end %>

3.0.beta3/app/views/tasks/_task.html.erb
<tr id="<%= dom_id task %>">
  <td><%= task.name %></td>
  <td><%= task.description %></td>
  <td><%= task.due_date %></td>
  <td><%= task.finished %></td>
  <td><%= link_to "Show", task %></td>
  <td><%= link_to "Edit", edit_task_path(task), :remote => true %></td>
  <td><%= link_to "Destroy", task, :confirm => 'Are you sure?', :method => :delete, :remote => true %></td>
</tr>

3.0.beta3/app/views/tasks/create.js.erb
$('<%= escape_javascript(render(:partial => @task))%>').appendTo('#tasks');
$("#new_task")[0].reset();

3.0.beta3/app/views/tasks/destroy.js.erb
$('#<%= dom_id @task %>').remove();

3.0.beta3/app/views/tasks/edit.html.erb
<% title "Edit Task" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @task %> |
  <%= link_to "View All", tasks_path %>
</p>

3.0.beta3/app/views/tasks/edit.js.erb
$("#form > form").replaceWith("<%= escape_javascript(render(:partial => "form"))%>")

3.0.beta3/app/views/tasks/index.html.erb
<% title "Task List" %>

<table id="tasks">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Due Date</th>
    <th>Finished</th>
  </tr>
  <% for task in @tasks %>
    <%= render task %>
  <% end %>
</table>

<h2>Task Form</h2>
<div id="form">
  <%= render :partial => "form" %>
</div>

3.0.beta3/app/views/tasks/new.html.erb
<% title "New Task" %>

<%= render 'form' %>

<p><%= link_to "Back to List", tasks_path %></p>

3.0.beta3/app/views/tasks/show.html.erb
<% title "Task" %>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>
<p>
  <strong>Due Date:</strong>
  <%= @task.due_date %>
</p>
<p>
  <strong>Finished:</strong>
  <%= @task.finished %>
</p>

<p>
  <%= link_to "Edit", edit_task_path(@task) %> |
  <%= link_to "Destroy", @task, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", tasks_path %>
</p>

3.0.beta3/app/views/tasks/update.js.erb
$("#<%= dom_id(@task) %>").replaceWith("<%= escape_javascript(render(:partial => @task)) %>");
<% @task = Task.new # reset for new form %>
$(".edit_task").replaceWith("<%= escape_javascript(render(:partial => "form"))%>")
$(".new_task")[0].reset();